export * from './makeCreatePartnerController'
export * from './makeFindOnePartnerController'
export * from './makeFindManyPartnersController'
export * from './makeUpdatePartnerController'
export * from './makeDeletePartnerController'
